site_name: Python Floripa
pages:
    - Home: index.md
    - Encontros: encontros.md
    - Empresas: empresas.md
    - Jobs: jobs.md
theme_dir: theme
include_next_prev: false
include_toc: false
remote_branch: master
remote_name: deploy
